[2024-05-01 06:02:24,510] [ERROR] Error checking service apiRest2: HTTPConnectionPool(host='localhost', port=8090): Max retries exceeded with url: /api/v1/actuator/health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000029EB4326BA0>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión'))
[2024-05-01 06:02:52,784] [ERROR] Error checking service apiRest2: HTTPConnectionPool(host='localhost', port=8090): Max retries exceeded with url: /api/v1/actuator/health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002918B2D5460>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión'))
[2024-05-01 06:03:02,770] [ERROR] Error checking service apiRest2: HTTPConnectionPool(host='localhost', port=8090): Max retries exceeded with url: /api/v1/actuator/health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002918B2D6840>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión'))
[2024-05-01 06:03:43,749] [ERROR] Error checking service apiRest2: HTTPConnectionPool(host='localhost', port=8090): Max retries exceeded with url: /api/v1/actuator/health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E7B6995550>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión'))
[2024-05-01 06:03:53,739] [ERROR] Error checking service apiRest2: HTTPConnectionPool(host='localhost', port=8090): Max retries exceeded with url: /api/v1/actuator/health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E7B6996060>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión'))
[2024-05-01 06:04:03,737] [ERROR] Error checking service apiRest2: HTTPConnectionPool(host='localhost', port=8090): Max retries exceeded with url: /api/v1/actuator/health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E7B6996AE0>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión'))
[2024-05-01 06:04:13,719] [ERROR] Error checking service apiRest2: HTTPConnectionPool(host='localhost', port=8090): Max retries exceeded with url: /api/v1/actuator/health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E7B6996870>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión'))
[2024-05-01 06:04:30,477] [ERROR] Error checking service apiRest2: HTTPConnectionPool(host='localhost', port=8090): Max retries exceeded with url: /api/v1/actuator/health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000219C60A55B0>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión'))
[2024-05-01 06:04:40,482] [ERROR] Error checking service apiRest2: HTTPConnectionPool(host='localhost', port=8090): Max retries exceeded with url: /api/v1/actuator/health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000219C60A5F10>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión'))
[2024-05-01 06:04:50,499] [ERROR] Error checking service apiRest2: HTTPConnectionPool(host='localhost', port=8090): Max retries exceeded with url: /api/v1/actuator/health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000219C60A6960>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión'))
[2024-05-01 06:06:00,967] [ERROR] Error checking service apiRest2: HTTPConnectionPool(host='localhost', port=8090): Max retries exceeded with url: /api/v1/actuator/health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022426C35550>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión'))
[2024-05-01 06:08:58,076] [ERROR] Error checking service apiRest2: HTTPConnectionPool(host='localhost', port=8090): Max retries exceeded with url: /api/v1/actuator/health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024871841700>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión'))
[2024-05-01 06:09:08,071] [ERROR] Error checking service apiRest2: HTTPConnectionPool(host='localhost', port=8090): Max retries exceeded with url: /api/v1/actuator/health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024871841E50>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión'))
[2024-05-01 06:11:58,839] [INFO] Service health check
[2024-05-01 06:23:39,885] [INFO] Service apiRest registered successfully
[2024-05-01 06:23:53,953] [ERROR] Error checking service apiRest: HTTPConnectionPool(host='localhost', port=8090): Max retries exceeded with url: /api/v1/actuator/health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002C8753707A0>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión'))
[2024-05-01 06:26:30,457] [ERROR] Error checking service apiRest: HTTPConnectionPool(host='localhost', port=8090): Max retries exceeded with url: /api/v1/actuator/health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001CC29E4AD50>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión'))
[2024-05-01 06:26:37,692] [INFO] Service apiRest registered successfully
[2024-05-01 06:26:51,739] [ERROR] Error checking service apiRest: HTTPConnectionPool(host='localhost', port=8090): Max retries exceeded with url: /api/v1/actuator/health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001CC2A051AF0>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión'))
[2024-05-01 06:27:01,736] [ERROR] Error checking service apiRest: HTTPConnectionPool(host='localhost', port=8090): Max retries exceeded with url: /api/v1/actuator/health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001CC2A052D80>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión'))
[2024-05-01 06:27:11,798] [ERROR] Error checking service apiRest: HTTPConnectionPool(host='localhost', port=8090): Max retries exceeded with url: /api/v1/actuator/health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001CC2A0536E0>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión'))
[2024-05-01 06:27:21,775] [ERROR] Error checking service apiRest: HTTPConnectionPool(host='localhost', port=8090): Max retries exceeded with url: /api/v1/actuator/health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001CC2A052DE0>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión'))
[2024-05-06 16:46:25,008] [ERROR] Error checking service apiRest: HTTPConnectionPool(host='api-rest', port=8090): Max retries exceeded with url: /api/v1/actuator/health (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x0000020767C31A00>: Failed to resolve 'api-rest' ([Errno 11001] getaddrinfo failed)"))
[2024-05-06 16:46:34,998] [ERROR] Error checking service apiRest: HTTPConnectionPool(host='api-rest', port=8090): Max retries exceeded with url: /api/v1/actuator/health (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x0000020767C32210>: Failed to resolve 'api-rest' ([Errno 11001] getaddrinfo failed)"))
[2024-05-06 16:46:45,026] [ERROR] Error checking service apiRest: HTTPConnectionPool(host='api-rest', port=8090): Max retries exceeded with url: /api/v1/actuator/health (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x0000020767C32B70>: Failed to resolve 'api-rest' ([Errno 11001] getaddrinfo failed)"))
[2024-05-06 16:46:55,026] [ERROR] Error checking service apiRest: HTTPConnectionPool(host='api-rest', port=8090): Max retries exceeded with url: /api/v1/actuator/health (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x0000020767C33470>: Failed to resolve 'api-rest' ([Errno 11001] getaddrinfo failed)"))
[2024-05-06 16:47:05,010] [ERROR] Error checking service apiRest: HTTPConnectionPool(host='api-rest', port=8090): Max retries exceeded with url: /api/v1/actuator/health (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x0000020767C32840>: Failed to resolve 'api-rest' ([Errno 11001] getaddrinfo failed)"))
